### ISSUE TITLE
How to use the scripts?

### ISSUE THREAD

**Issue by anmol26s** [maniackcrudelis/Fallback-server#1]
Hi
Can you please tell how to run the scripts step by step please.

**Comment by maniackcrudelis** [comment]
Hi

You can probably find more informations with the readme of the associated app
https://github.com/YunoHost-Apps/fallback_ynh/blob/master/README.md

If not, please explain me what you want to do exactly.

**Comment by anmol26s** [comment]
I did not see that page. I will test it.
Thanks
